name: tabbed_card
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/raulsaba/tabbed_card

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: