name: tabbed_card
description: It is a custom card with Tabs for keeps multiple contents.
version: 0.0.2
homepage: https://github.com/raulsaba/tabbed_card

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: